esphome:
  name: wemos-d1-uno
  platform: ESP8266
  board: esp12e
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "73e88eeefa70b926021e6bd7bf64a85e"

wifi:
  ssid: "qsvMIMt8Fm6NV3"
  password: "UbKNUJakLBLpOh"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos-D1-Uno Fallback Hotspot"
    password: "ofkY4QoUscpe"

captive_portal:

# Example configuration entry
dallas:
  - pin: GPIO13
    update_interval: 10s

# Individual sensors
sensor:
  - platform: dallas
    address: 0xD201144A8ED4AA28
    name: "Uno Temperature"
    id: wemos_d1_temperature

# Example configuration entry
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO12
    num_leds: 1
    rgb_order: GRB
    name: "Uno WS2812 LED"
    id: wemos_d1_led